# Generated by Django 2.2.2 on 2019-06-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20190619_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='quote',
            field=models.TextField(default=True, null=True),
        ),
    ]
