# Generated by Django 2.2.2 on 2019-06-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20190619_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='punchLine',
            field=models.CharField(default=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='quote',
            field=models.CharField(default=True, max_length=500, null=True),
        ),
    ]
