# Generated by Django 2.2.2 on 2019-06-19 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20190619_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='punchLine',
            new_name='block_quote',
        ),
    ]
