# Generated by Django 2.2.2 on 2019-06-19 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20190619_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='block_quote',
        ),
    ]
