# Generated by Django 2.2.2 on 2019-06-20 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_remove_post_block_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='writer',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
