# Generated by Django 2.2.2 on 2019-06-20 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20190620_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slide_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='pictures/%Y/%m/%d/'),
        ),
    ]
