# Generated by Django 2.2.2 on 2019-06-21 14:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='published',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
