# Generated by Django 2.2.2 on 2019-06-22 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_post_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='field',
        ),
    ]
