# Generated by Django 2.2.2 on 2019-07-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_post_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='field',
        ),
        migrations.AddField(
            model_name='post',
            name='fashion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='food',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='lifestyle',
            field=models.BooleanField(default=False),
        ),
    ]
